# .github/dependabot.yml

version: 2
updates:
  # 更新 npm (JavaScript) 依赖
  - package-ecosystem: "npm"
    directory: "/" # package.json 所在的位置
    schedule:
      interval: "weekly" # 每周一检查
    ignore:
      - dependency-name: "eslint"
        versions: ["> 8"]
    commit-message:
      prefix: "build(packages):" # PR 合并提交信息的前缀
